### ISSUE TITLE
FormDiagram.from_graph bug 

### ISSUE THREAD

**Issue by duchaoyu** [BlockResearchGroup/compas_ags#37] opened 2020-07-30 08:56 UTC
I'm trying to check the FormGraph before the user generate a FormDiagram from it. 
Planarity can be checked smoothly without any problem. Another thing I wanna check is that often the user draws a "L"- node without external forces on that node and this node could never achieve equilibrium. So I check the graph and delete these nodes. 

When I generate the FormDiagram using from_graph, it uses the method of `form = cls.from_vertices_and_faces(points, cycles)`
which means the `faces` still uses the old keys, which may not correspond to the new keys. 

for example:
![image](https://user-images.githubusercontent.com/43376817/88902469-88a6b780-d252-11ea-9141-c5841ab7d858.png)

graph, node key [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] -> delete node key [0, 2] -> now the existing keys would be [1, 3, 4, 5, 6, 7, 8, 9] -> `graph.to_points() `would give the coordinates of these exisitng 8 points, and their new key in the FormDiagram would be [0, 1, 2, 3, 4, 5, 6, 7] instead of [1, 3, 4, 5, 6, 7, 8, 9]. But `cycles = network_find_cycles(graph, breakpoints=graph.leaves())` uses the old keys [1, 3, 4, 5, 6, 7, 8, 9]. ooops ... key error

Now i fixed it in the cmd before generating the FormDiagram, but I think this is not ideal. I'm a bit unsure whether this should be fixed in Compas....

**Comment by juney-lee** [comment] 2020-07-30 13:44
After the form diagram has been created, what about:

For all boundary vertices, it vertex is not a leaf vertex, and if vertex has valency of two, delete the vertex from the form diagram.

**Comment by duchaoyu** [comment] 2020-07-30 13:49
that's also possible...
Do you think this is better...? I'm a bit perfectionism andI hope the vertex keys are clean.... (maybe it doesn't matter... )

**Comment by brgcode** [comment] 2020-08-01 12:20
i am not sure i understand the problem. in the drawing, where are the "L" nodes? why would it not be possible to achieve equilibrium in nodes 0 and 2?

**Comment by brgcode** [comment] 2020-08-01 12:24
the second part about vertex numbering is indeed a bug. however, it can and should be fixed within the `from_graph` function...

**Comment by duchaoyu** [comment] 2020-08-03 08:13
> i am not sure i understand the problem. in the drawing, where are the "L" nodes? why would it not be possible to achieve equilibrium in nodes 0 and 2?
if there's no external force on the L node {2} and {0}, there's only one possiblity is that both edge has 0 force. This would be an error in AGS. That's why I try to remove them.

**Comment by brgcode** [comment] 2020-08-03 08:28
okay but that doesn't make any sense. we can't just delete parts of a valid structure simply because of a bug in AGS.

after deleting those nodes the structure is no longer the same. the force in those edges is only zero because of the specific geometry and boundary conditions. if the geometry is changed or the boundary conditions are changed, any resulting solutions are no longer related to the original structure.

the problem with zero-force edges just needs to be solved...

**Comment by duchaoyu** [comment] 2020-08-03 08:37
![image](https://user-images.githubusercontent.com/43376817/89163081-590aee80-d575-11ea-93a7-cb282e3bd7a8.png)

**Comment by brgcode** [comment] 2020-08-03 10:58
the problem is actually not related to the fact that there is no force in the edges. it is a bit more complicated and can't easily be solved. the problem is that for the situation you described there is actually no valid dual for the form diagram. 

consider node `17` and let's say that the big outside face of the diagram is `1` and the face formed by edges `27, 31, 29` is face `2`. in the dual, the edges corresponding to `29` and `31` would both connect to the dual vertices of faces `1` and `2`, which means that there would have to be two edges between those vertices. 

this is not possible with our data structures and indeed breaks the theoretical framework of AGS. the diagrams are nevertheless constructed (albeit not correctly), but calculations involving the force diagram will fail because of a dimension  mismatch between the connectivity matrices of form and force.

there is thus no problem with collapsed edges not having an orientation or anything like that, but rather with the fact that form and force are not dual/reciprocal.

solving this behind the scenes is currently not realistic. therefore, i propose that we indeed remove 2-valent nodes from the graph as you suggested before making the form diagram and to renumber accordingly (i already pushed an update for that), but perhaps we should keep the underlying graph and visualise it in the background to clarify that there is a difference between the connectivity graph of the provided lines and the valid corresponding form diagram.

to be discussed...

**Closed** 2020-08-03 11:05 UTC
Labels: enhancement, question
